### ISSUE TITLE
Documentation should include alarms or other resources

### ISSUE THREAD

**Issue by martinb3** [rackerlabs/jetstream#50]
We originally took out the list of "all resources" in the markdown / documentation produced by jetstream, but it's recently been suggested that having a list of alarms defined would be useful (see idea 136). Should we (a) add the alarms to the output or (b) add all the resources back, grouped by type?

**Comment by jonathan-madison** [comment]
Relevant links:

- https://app.prodpad.com/ideas/136/canvas
- https://github.com/rax-brazil/TroposphereTemplates/issues/509

What was the rationale for removing it to begin with? I wasn't able to find an old issue in this repo.

Based on the Prodpad idea, I think along with the template READMEs Support would also value generating a single, central document detailing:

- Alarms in each template
- Thresholds
- Actions

Just stating explicitly so that ask is discussed and not lost in discussion of the existing READMEs.

**Comment by martinb3** [comment]
Closing this issue, as we're going to override the documentation in our specific project using the tool.
