### ISSUE TITLE
Python 2/3 support migration plan

### ISSUE THREAD

**Issue by cwgem** [rackerlabs/jetstream#91]
Given the age of the previous python 3 bug, #46 I'm opening this one up to have a more current issue that folks don't miss due to the age of the previous one. Put simply, I've been able to get a working python 3 version of jetstream. The essential work for this can be found here:

https://github.com/rackerlabs/jetstream/commit/7f8537c5a1974297c7f238eff7a43fbd1b3abb91

Mostly copying from the commit log:

* items(), keys(), and many other funcitons now return specific objects instead of a list, so they need to be explicitly converted in some areas (mostly a NOOP on python 2)
* `cmp` is deprecated in python 3 so use `==` instead (also works on python 2)
* Raising of exceptions are formatted differently. This code is python 3 specific
* Usage of sys.stderr.write versus the print function. This code is python 3 specific
* Modification of dynamic module import code to use inject the current directory into sys.path so that module imports work properly when not in system path. Temporary modifications to the path are reset to the original so as to avoid unnecessary import consequences
* Fix test scripts to use proper relative imports

In particular:

* Raising of exceptions are formatted differently - This I can't make 2 backwards compatible due to the lexer bombing out
* sage of sys.stderr.write versus the print function - This I can't make 2 backwards compatible due to __future__ imports needing to be the absolute top level import (meaning I can't wrap a try/catch or if block around it)

Given these changes, I'd like to have the next release be python 3 specific. Given that there are tagged release now, folks who still need time to migrate from 2 will be able to stay on that release instead. I'll also look into creating a somewhat basic migration guide based on the work I've done internally on some of the template code. Note that there is a "python 3" version of troposphere, but it's somewhat of a `2to3.py` on the backend and I'd rather have that as a solid python 3 master branch.

**Comment by johnctitus** [comment]
> * Raising of exceptions are formatted differently - This I can't make 2 backwards compatible due to the lexer bombing out

Guess I am confused about this.  The line `raise Exception("Test Exception")` is valid in both python 2 and python 3.  Unless my search-fu is broken, the only see two places in the code I see where we are not doing the above is at: https://github.com/rackerlabs/jetstream/blob/4338260216bdfd3641e1152a31c09531b984e932/jetstream/template.py#L40  and https://github.com/rackerlabs/jetstream/blob/4338260216bdfd3641e1152a31c09531b984e932/jetstream/template.py#L291 Can we not just output the diagnostic message and reraise the error?  Its not an exact duplication of functionality, but accomplishes the same thing.

> * sage of sys.stderr.write versus the print function - This I can't make 2 backwards compatible due to **future** imports needing to be the absolute top level import (meaning I can't wrap a try/catch or if block around it)

Can we instead move to a method that is python 2 compatible.  It looks like the logging module is compatible with both python 2 and python 3, and allows comparable results.  Little more work, but probably leaves us in a better place, and gives us the capability of adding additional diagnostic info\verbosity down the road.

> * Modification of dynamic module import code to use inject the current directory into sys.path so that module imports work properly when not in system path. Temporary modifications to the path are reset to the original so as to avoid unnecessary import consequences

Not sure how I feel about this, especially as its not really related to the python 2->3 conversion.  As it stands now, if the template module is properly setup in python, jetstream should be able to process it.  Changing this functionality should be spun into a separate issue for discussion.

**Comment by jarosser06** [comment]
Jetstream should remain backwards compatible for Python2, it is an open source project the work needed to maintain that backwards compatibility is very minimal. In fact that work was already done [here](https://github.com/rackerlabs/jetstream/pull/74/files). 

After reviewing your linked commit one piece in particular stood out; converting .keys() to a proper list is unnecessary. Why would that need to be an actual list when the returned Python object supports iteration and the [__contains__ method](https://docs.python.org/3/reference/datamodel.html#object.__contains__).

Your code here for example
```python
if 'Metadata' in list(current_template.keys())\
            and TOPLEVEL_METADATA_KEY in list(current_template['Metadata'].keys()):
```
Does nothing more than unnecessary type conversion since the original code would still work in Python3 just fine.

Again the work was already done once and as stated in the original PR, last I checked the only blocker is infinite recursion when deepcopy() is called on the Troposphere objects. I've already discussed a workaround with @gdelvalle which involves re-reading the templates again rather than copying the existing Python objects. This would not be efficient but it does handle the issue for the time being until it gets resolved upstream.

**Comment by cwgem** [comment]
@johnctitus 

`Not sure how I feel about this, especially as its not really related to the python 2->3 conversion` Doing `cwd` runs without the faws-templates module installed worked fine for me in python 2 world, which is why when it didn't work in python 3 I did the add to fix it. If it didn't work for python 2 I wouldn't be as concerned much and instead add it as an enhancement. 

@jarosser06 

Didn't know `in` type was supported by the new filter objects. Only a mere mortal unfortunately. I also don't know about the infinite recursion bug being mentioned. When doing the run with my changes the test templates as well as internal templates everything was output just fine. Not sure what to make of that unfortunately.

Will have to see what merging needs to be done from #74 . Also from this part of the PR:

https://github.com/rackerlabs/jetstream/pull/74/commits/cead6e0b9d78cbe9809cf72c8c3797446f2de11a

We used a simple `==` comparison and found it to work out fine. Did you find any gotchas with that method which required the fix in the commit above to be used?

**Comment by gdelvalle** [comment]
FWIW, I recently ran  jetstream locally using  @jarosser06 's branch and hit the recursion bug he is talking about.  It only happened when I was doing the full test that stands up Cloudformation stacks.

**Comment by johnctitus** [comment]
The had not thought about the possibility of a recursion loop with deepcopy.  Maybe instead of using deepcopy, we can call the template `to_dict()` method and make our modifications there.  It appears that method does create an actual copy, and does not pass any existing references.  Would need to update the metadata, deletion policy, and generation sections slightly, but should be doable without too much grief.

Poked at it a bit and was able to generate a test run without any error and with the created artifacts and test templates generated as expected

```
> git diff
diff --git a/jetstream/template.py b/jetstream/template.py
index 0ac8230..fc51922 100644
--- a/jetstream/template.py
+++ b/jetstream/template.py
@@ -262,14 +262,11 @@ class JetstreamTemplate(object):
         # validation steps and proper resource name
         self._required_attrs(['template', 'name'])

-        tmpl = self.template
+        tmpl = self.template.to_dict()
         # Remove DeletionPolicies for templates during testing
         if testing:
-            # We are going to modify this template during testing
-            # but do not want to affect the original.
-            tmpl = copy.deepcopy(self.template)
-            for _, resource in tmpl.resources.items():
-                resource.resource['DeletionPolicy'] = 'Delete'
+            for _, resource in tmpl['Resources'].items():
+                resource['DeletionPolicy'] = 'Delete'

         try:
             if additional_metadata:
@@ -277,11 +274,11 @@ class JetstreamTemplate(object):
                     additional_metadata)

                 if jetstream_metadata:
-                    tmpl.metadata[TOPLEVEL_METADATA_KEY] = jetstream_metadata
+                    tmpl['Metadata'][TOPLEVEL_METADATA_KEY] = jetstream_metadata

             # Handle JSON.dumps failing
             encoded_template = json.dumps(
-                tmpl.to_dict(),
+                tmpl,
                 sort_keys=False, indent=2,
                 separators=(',', ': '),
                 cls=JetstreamEncoder)
> jetstream --package test_templates --test --dry-test
Updated Templates: s3.template, ec2.template
```

Code worked in both python 2 and 3 so I think that should resolve that bit, although could probably use a bit more in depth testing.

**Comment by cwgem** [comment]
Closing this out now that all code has been merged into master.
